name: Build and tag
on:
  push:
    branches:
      - main # Default release branch
jobs:
  BuildAndTag:
    name: build and tag
    runs-on: windows-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        shell: pwsh
        run: dotnet restore

      - name: Build
        shell: pwsh
        run: dotnet build --no-restore

      # TODO: Change get version action
      - name: package-version
        shell: pwsh
        run: |
          $xml = [Xml] (Get-Content src/LottoMk2.App/LottoMk2.App.csproj)
          $version = [Version] $xml.Project.PropertyGroup.Version
          echo "::set-output name=version::$version"
          echo "::debug::{version=$version}"
        id: get_package_version

      - name: Check tag
        uses: bbonkr/git-tag-check-action@v1.0.9
        id: check_tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ steps.get_package_version.outputs.version }}"

      - name: package-version-to-git-tag
        uses: pkgdeps/git-tag-action@v2
        if: ${{ steps.check_tag.outputs.tag == '' }}
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ steps.get_package_version.outputs.version }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"

      - name: Release Drafter
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        if: ${{ steps.check_tag.outputs.tag == '' }}
        with:
          config-name: release-drafter.yml
          version: ${{ steps.get_package_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Check Upload Url
        if: ${{ steps.check_tag.outputs.tag == '' }}
        run: echo "${{ steps.release_drafter.outputs.upload_url }}"

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        if: ${{ steps.check_tag.outputs.tag == '' }}
        with:
          token: ${{ secrets.GH_TOKEN }}
          # repository: bbonkr/Lotto-mk2
          event-type: upload-assets
          client-payload: '{ "url": "${{ steps.release_drafter.outputs.upload_url }}" }'